# Model
model: EASE

# Reproducibility
seed: 2025
reproducibility: true

# Regularisation parameter
reg_weight: 250.0

# Batch sizes
train_batch_size: 2048
eval_batch_size: 4096

# Runtime output
state: INFO
show_progress: true

# CPU execution
use_gpu: false
